# Generated by Django 5.1.5 on 2025-01-31 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date',
            field=models.DateField(default='2999-12-31'),
        ),
    ]
